### PR TITLE
Fixed consistency of custom property documentation

### PR DESCRIPTION
**Pull request by robrez**
In the documentation for all other elements, the property name and default value of a given custom property are surrounded with backticks so that they read like inline-code.

paper-progress does not currently follow this convention.

### CODE REVIEW

**Comment by robrez** [comment]
Updated patch --

I noticed that paper-progress was incorrectly using `--paper-progress-active-active-color` instead of `--paper-progress-disabled-secondary-color`

**Comment by blasten** [comment]
LGTM. Can you rebase your branch pls?

**Comment by robrez** [comment]
Hopefully I did that correctly. My git skills need improvement. :octocat:

**Comment by blasten** [comment]
@robrez I can't merge until you rebase and fix the conflicts.  To rebase, switch to the master branch and pull the latest changes and then switch back to your branch and run `git rebase master`. You may have a few conflicts to resolve.

**Comment by robrez** [comment]
Now, I think, I've really made a mess of things by doing a 'merge' - 
https://help.github.com/articles/syncing-a-fork/

You're probably shaking your head at this point :). Before I try to undo the merge - can you confirm that the current state of things is not ideal for you. Sorry for making this way more difficult than it should be!

**Comment by blasten** [comment]
LGTM. Also @tedium-bot will generate the readme automatically, so you don't need to update readme.md

**Pull request merged**
