### PR TITLE
Fix transiting class

### PR DESCRIPTION
**Pull request by blasten**
I forgot to check this. I added a test now.

### CODE REVIEW

**Comment by frankiefu** [comment]
LGTM

**Comment by avinoamr** [comment]
@blasten when do you plan to release it in a new tagged version?

**Comment by blasten** [comment]
there you go: https://github.com/PolymerElements/paper-progress/releases/tag/v1.0.5

**Comment by avinoamr** [comment]
Awesome. Thanks @blasten  :)

**Pull request merged**
